openapi: 3.0.3
info:
  title: Restaurant API
  description: STD23042
  version: '1.0.0'

servers:
  - url: http://localhost:8080
    description: Local server

tags:
  - name: Health
    description: Health check endpoints
  - name: Ingredients
    description: Operations related to ingredients

paths:
  /ping:
    get:
      tags:
        - Health
      summary: Health check endpoint
      operationId: ping
      responses:
        '200':
          description: Pong response
          content:
            text/plain:
              schema:
                type: string
                example: pong

  /ingredients:
    get:
      tags:
        - Ingredients
      summary: Get ingredients with optional price filters
      operationId: getIngredients
      parameters:
        - name: priceMinFilter
          in: query
          required: false
          schema:
            type: number
            format: double
        - name: priceMaxFilter
          in: query
          required: false
          schema:
            type: number
            format: double
      responses:
        '200':
          description: List of ingredients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ingredient'
        '400':
          description: Invalid price filter
    post:
      tags:
        - Ingredients
      summary: Add new ingredients
      operationId: addIngredients
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Ingredient'
      responses:
        '201':
          description: Ingredients created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ingredient'
    put:
      tags:
        - Ingredients
      summary: Update existing ingredients
      operationId: updateIngredients
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Ingredient'
      responses:
        '200':
          description: Updated ingredients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ingredient'

  /ingredients/{id}:
    get:
      tags:
        - Ingredients
      summary: Get ingredient by ID
      operationId: getIngredient
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Found ingredient
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
        '404':
          description: Ingredient not found
    delete:
      tags:
        - Ingredients
      summary: Delete ingredient by ID
      operationId: deleteIngredient
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Ingredient deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'

components:
  schemas:
    Ingredient:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        updateDatetime:
          type: string
          format: date-time
        unitPrice:
          type: number
          format: double
        unit:
          type: string